### ISSUE TITLE
Component can't be reset

### ISSUE THREAD

**Issue by sebj8** [nachocinalli/adapt-fillin#1]
When question is reset after fail attempt, answers are not reset and can't be change, click cause error:
Uncaught TypeError: lastActiveItem is undefined

I use no feedback and unlimited (-1) attempts. 
![error](https://github.com/user-attachments/assets/aa99d8f2-6821-44f1-aabd-dc5d66a89846)

**Comment by nachocinalli** [comment]
Thanks @sebj8,  I have updated the component. Could you please try it again?

**Comment by sebj8** [comment]
Now it's perfect, flawless!
I really like this component, it is present in MOODLE and this is what I was missing in ADAPT. **Thank you for solving the problem quickly**.

**Comment by EGeorge13** [comment]
I have been looking at this component as well, thank you for the fix!
