### ISSUE TITLE
Add an Reset Button

### ISSUE THREAD

**Issue by EGeorge13** [nachocinalli/adapt-fillin#2]
Hi, this is a request for extra functionality,
So I like how you can select the options to reset options out of the selected spot, but my clients are requesting the possibility of a reset button? They are saying the method of undoing a selection is currently unintuitive to them, especially when there are two or more selections to make.
Thank you :)

**Comment by nachocinalli** [comment]
Hi @EGeorge13,
Can you test the functionality on [the issue/2 branch](https://github.com/nachocinalli/adapt-fillin/archive/refs/heads/issue/2.zip)?

**Comment by EGeorge13** [comment]
Thank you @nachocinalli, the button works very well!
Again thank you for responding so quickly!
